/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'institution' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const College = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'collegeType' : IDL.Text,
  'state' : IDL.Text,
});
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'file' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'resourceType' : IDL.Text,
  'uploadedBy' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'semester' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCollege' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addState' : IDL.Func([IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'addYear' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllYears' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollegesByState' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
  'getResourcesBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getSubjectsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCollege' : IDL.Func([IDL.Text], [], []),
  'removeResource' : IDL.Func([IDL.Text], [], []),
  'removeState' : IDL.Func([IDL.Text], [], []),
  'removeSubject' : IDL.Func([IDL.Text], [], []),
  'removeYear' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchColleges' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
  'searchResources' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
  'searchSubjects' : IDL.Func([IDL.Text], [IDL.Vec(Subject)], ['query']),
  'uploadResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'institution' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const College = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'collegeType' : IDL.Text,
    'state' : IDL.Text,
  });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'file' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'resourceType' : IDL.Text,
    'uploadedBy' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'semester' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCollege' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addState' : IDL.Func([IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'addYear' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllYears' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollegesByState' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
    'getResourcesBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getSubjectsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCollege' : IDL.Func([IDL.Text], [], []),
    'removeResource' : IDL.Func([IDL.Text], [], []),
    'removeState' : IDL.Func([IDL.Text], [], []),
    'removeSubject' : IDL.Func([IDL.Text], [], []),
    'removeYear' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchColleges' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
    'searchResources' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
    'searchSubjects' : IDL.Func([IDL.Text], [IDL.Vec(Subject)], ['query']),
    'uploadResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };