/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface College {
  'id' : string,
  'name' : string,
  'collegeType' : string,
  'state' : string,
}
export interface Resource {
  'id' : string,
  'title' : string,
  'subject' : string,
  'file' : [] | [Uint8Array],
  'resourceType' : string,
  'uploadedBy' : string,
}
export interface Subject {
  'id' : string,
  'semester' : bigint,
  'code' : string,
  'name' : string,
  'year' : bigint,
}
export interface UserProfile {
  'institution' : [] | [string],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCollege' : ActorMethod<[string, string, string], undefined>,
  'addState' : ActorMethod<[string], undefined>,
  'addSubject' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'addYear' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllStates' : ActorMethod<[], Array<string>>,
  'getAllYears' : ActorMethod<[], Array<bigint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollegesByState' : ActorMethod<[string], Array<College>>,
  'getResourcesBySubject' : ActorMethod<[string], Array<Resource>>,
  'getSubjectsByYear' : ActorMethod<[bigint], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCollege' : ActorMethod<[string], undefined>,
  'removeResource' : ActorMethod<[string], undefined>,
  'removeState' : ActorMethod<[string], undefined>,
  'removeSubject' : ActorMethod<[string], undefined>,
  'removeYear' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchColleges' : ActorMethod<[string], Array<College>>,
  'searchResources' : ActorMethod<[string], Array<Resource>>,
  'searchSubjects' : ActorMethod<[string], Array<Subject>>,
  'uploadResource' : ActorMethod<
    [string, string, string, Uint8Array],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];